	soc_system u0 (
		.camera_controller_0_conduit_camera_pixclk      (<connected-to-camera_controller_0_conduit_camera_pixclk>),      // camera_controller_0_conduit_camera.pixclk
		.camera_controller_0_conduit_camera_frame_valid (<connected-to-camera_controller_0_conduit_camera_frame_valid>), //                                   .frame_valid
		.camera_controller_0_conduit_camera_line_valid  (<connected-to-camera_controller_0_conduit_camera_line_valid>),  //                                   .line_valid
		.camera_controller_0_conduit_camera_cam_reset   (<connected-to-camera_controller_0_conduit_camera_cam_reset>),   //                                   .cam_reset
		.camera_controller_0_conduit_camera_data_in     (<connected-to-camera_controller_0_conduit_camera_data_in>),     //                                   .data_in
		.clk_clk                                        (<connected-to-clk_clk>),                                        //                                clk.clk
		.hps_0_ddr_mem_a                                (<connected-to-hps_0_ddr_mem_a>),                                //                          hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                               (<connected-to-hps_0_ddr_mem_ba>),                               //                                   .mem_ba
		.hps_0_ddr_mem_ck                               (<connected-to-hps_0_ddr_mem_ck>),                               //                                   .mem_ck
		.hps_0_ddr_mem_ck_n                             (<connected-to-hps_0_ddr_mem_ck_n>),                             //                                   .mem_ck_n
		.hps_0_ddr_mem_cke                              (<connected-to-hps_0_ddr_mem_cke>),                              //                                   .mem_cke
		.hps_0_ddr_mem_cs_n                             (<connected-to-hps_0_ddr_mem_cs_n>),                             //                                   .mem_cs_n
		.hps_0_ddr_mem_ras_n                            (<connected-to-hps_0_ddr_mem_ras_n>),                            //                                   .mem_ras_n
		.hps_0_ddr_mem_cas_n                            (<connected-to-hps_0_ddr_mem_cas_n>),                            //                                   .mem_cas_n
		.hps_0_ddr_mem_we_n                             (<connected-to-hps_0_ddr_mem_we_n>),                             //                                   .mem_we_n
		.hps_0_ddr_mem_reset_n                          (<connected-to-hps_0_ddr_mem_reset_n>),                          //                                   .mem_reset_n
		.hps_0_ddr_mem_dq                               (<connected-to-hps_0_ddr_mem_dq>),                               //                                   .mem_dq
		.hps_0_ddr_mem_dqs                              (<connected-to-hps_0_ddr_mem_dqs>),                              //                                   .mem_dqs
		.hps_0_ddr_mem_dqs_n                            (<connected-to-hps_0_ddr_mem_dqs_n>),                            //                                   .mem_dqs_n
		.hps_0_ddr_mem_odt                              (<connected-to-hps_0_ddr_mem_odt>),                              //                                   .mem_odt
		.hps_0_ddr_mem_dm                               (<connected-to-hps_0_ddr_mem_dm>),                               //                                   .mem_dm
		.hps_0_ddr_oct_rzqin                            (<connected-to-hps_0_ddr_oct_rzqin>),                            //                                   .oct_rzqin
		.hps_0_io_hps_io_emac1_inst_TX_CLK              (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CLK>),              //                           hps_0_io.hps_io_emac1_inst_TX_CLK
		.hps_0_io_hps_io_emac1_inst_TXD0                (<connected-to-hps_0_io_hps_io_emac1_inst_TXD0>),                //                                   .hps_io_emac1_inst_TXD0
		.hps_0_io_hps_io_emac1_inst_TXD1                (<connected-to-hps_0_io_hps_io_emac1_inst_TXD1>),                //                                   .hps_io_emac1_inst_TXD1
		.hps_0_io_hps_io_emac1_inst_TXD2                (<connected-to-hps_0_io_hps_io_emac1_inst_TXD2>),                //                                   .hps_io_emac1_inst_TXD2
		.hps_0_io_hps_io_emac1_inst_TXD3                (<connected-to-hps_0_io_hps_io_emac1_inst_TXD3>),                //                                   .hps_io_emac1_inst_TXD3
		.hps_0_io_hps_io_emac1_inst_RXD0                (<connected-to-hps_0_io_hps_io_emac1_inst_RXD0>),                //                                   .hps_io_emac1_inst_RXD0
		.hps_0_io_hps_io_emac1_inst_MDIO                (<connected-to-hps_0_io_hps_io_emac1_inst_MDIO>),                //                                   .hps_io_emac1_inst_MDIO
		.hps_0_io_hps_io_emac1_inst_MDC                 (<connected-to-hps_0_io_hps_io_emac1_inst_MDC>),                 //                                   .hps_io_emac1_inst_MDC
		.hps_0_io_hps_io_emac1_inst_RX_CTL              (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CTL>),              //                                   .hps_io_emac1_inst_RX_CTL
		.hps_0_io_hps_io_emac1_inst_TX_CTL              (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CTL>),              //                                   .hps_io_emac1_inst_TX_CTL
		.hps_0_io_hps_io_emac1_inst_RX_CLK              (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CLK>),              //                                   .hps_io_emac1_inst_RX_CLK
		.hps_0_io_hps_io_emac1_inst_RXD1                (<connected-to-hps_0_io_hps_io_emac1_inst_RXD1>),                //                                   .hps_io_emac1_inst_RXD1
		.hps_0_io_hps_io_emac1_inst_RXD2                (<connected-to-hps_0_io_hps_io_emac1_inst_RXD2>),                //                                   .hps_io_emac1_inst_RXD2
		.hps_0_io_hps_io_emac1_inst_RXD3                (<connected-to-hps_0_io_hps_io_emac1_inst_RXD3>),                //                                   .hps_io_emac1_inst_RXD3
		.hps_0_io_hps_io_sdio_inst_CMD                  (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),                  //                                   .hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0                   (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),                   //                                   .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1                   (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),                   //                                   .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK                  (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),                  //                                   .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2                   (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),                   //                                   .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3                   (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),                   //                                   .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_usb1_inst_D0                   (<connected-to-hps_0_io_hps_io_usb1_inst_D0>),                   //                                   .hps_io_usb1_inst_D0
		.hps_0_io_hps_io_usb1_inst_D1                   (<connected-to-hps_0_io_hps_io_usb1_inst_D1>),                   //                                   .hps_io_usb1_inst_D1
		.hps_0_io_hps_io_usb1_inst_D2                   (<connected-to-hps_0_io_hps_io_usb1_inst_D2>),                   //                                   .hps_io_usb1_inst_D2
		.hps_0_io_hps_io_usb1_inst_D3                   (<connected-to-hps_0_io_hps_io_usb1_inst_D3>),                   //                                   .hps_io_usb1_inst_D3
		.hps_0_io_hps_io_usb1_inst_D4                   (<connected-to-hps_0_io_hps_io_usb1_inst_D4>),                   //                                   .hps_io_usb1_inst_D4
		.hps_0_io_hps_io_usb1_inst_D5                   (<connected-to-hps_0_io_hps_io_usb1_inst_D5>),                   //                                   .hps_io_usb1_inst_D5
		.hps_0_io_hps_io_usb1_inst_D6                   (<connected-to-hps_0_io_hps_io_usb1_inst_D6>),                   //                                   .hps_io_usb1_inst_D6
		.hps_0_io_hps_io_usb1_inst_D7                   (<connected-to-hps_0_io_hps_io_usb1_inst_D7>),                   //                                   .hps_io_usb1_inst_D7
		.hps_0_io_hps_io_usb1_inst_CLK                  (<connected-to-hps_0_io_hps_io_usb1_inst_CLK>),                  //                                   .hps_io_usb1_inst_CLK
		.hps_0_io_hps_io_usb1_inst_STP                  (<connected-to-hps_0_io_hps_io_usb1_inst_STP>),                  //                                   .hps_io_usb1_inst_STP
		.hps_0_io_hps_io_usb1_inst_DIR                  (<connected-to-hps_0_io_hps_io_usb1_inst_DIR>),                  //                                   .hps_io_usb1_inst_DIR
		.hps_0_io_hps_io_usb1_inst_NXT                  (<connected-to-hps_0_io_hps_io_usb1_inst_NXT>),                  //                                   .hps_io_usb1_inst_NXT
		.hps_0_io_hps_io_spim1_inst_CLK                 (<connected-to-hps_0_io_hps_io_spim1_inst_CLK>),                 //                                   .hps_io_spim1_inst_CLK
		.hps_0_io_hps_io_spim1_inst_MOSI                (<connected-to-hps_0_io_hps_io_spim1_inst_MOSI>),                //                                   .hps_io_spim1_inst_MOSI
		.hps_0_io_hps_io_spim1_inst_MISO                (<connected-to-hps_0_io_hps_io_spim1_inst_MISO>),                //                                   .hps_io_spim1_inst_MISO
		.hps_0_io_hps_io_spim1_inst_SS0                 (<connected-to-hps_0_io_hps_io_spim1_inst_SS0>),                 //                                   .hps_io_spim1_inst_SS0
		.hps_0_io_hps_io_uart0_inst_RX                  (<connected-to-hps_0_io_hps_io_uart0_inst_RX>),                  //                                   .hps_io_uart0_inst_RX
		.hps_0_io_hps_io_uart0_inst_TX                  (<connected-to-hps_0_io_hps_io_uart0_inst_TX>),                  //                                   .hps_io_uart0_inst_TX
		.hps_0_io_hps_io_i2c0_inst_SDA                  (<connected-to-hps_0_io_hps_io_i2c0_inst_SDA>),                  //                                   .hps_io_i2c0_inst_SDA
		.hps_0_io_hps_io_i2c0_inst_SCL                  (<connected-to-hps_0_io_hps_io_i2c0_inst_SCL>),                  //                                   .hps_io_i2c0_inst_SCL
		.hps_0_io_hps_io_i2c1_inst_SDA                  (<connected-to-hps_0_io_hps_io_i2c1_inst_SDA>),                  //                                   .hps_io_i2c1_inst_SDA
		.hps_0_io_hps_io_i2c1_inst_SCL                  (<connected-to-hps_0_io_hps_io_i2c1_inst_SCL>),                  //                                   .hps_io_i2c1_inst_SCL
		.hps_0_io_hps_io_gpio_inst_GPIO09               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO09>),               //                                   .hps_io_gpio_inst_GPIO09
		.hps_0_io_hps_io_gpio_inst_GPIO35               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO35>),               //                                   .hps_io_gpio_inst_GPIO35
		.hps_0_io_hps_io_gpio_inst_GPIO40               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO40>),               //                                   .hps_io_gpio_inst_GPIO40
		.hps_0_io_hps_io_gpio_inst_GPIO53               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO53>),               //                                   .hps_io_gpio_inst_GPIO53
		.hps_0_io_hps_io_gpio_inst_GPIO54               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO54>),               //                                   .hps_io_gpio_inst_GPIO54
		.hps_0_io_hps_io_gpio_inst_GPIO61               (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO61>),               //                                   .hps_io_gpio_inst_GPIO61
		.i2c_0_i2c_scl                                  (<connected-to-i2c_0_i2c_scl>),                                  //                          i2c_0_i2c.scl
		.i2c_0_i2c_sda                                  (<connected-to-i2c_0_i2c_sda>),                                  //                                   .sda
		.pll_0_cam2_clk_clk                             (<connected-to-pll_0_cam2_clk_clk>),                             //                     pll_0_cam2_clk.clk
		.pll_0_cam3_clk_clk                             (<connected-to-pll_0_cam3_clk_clk>),                             //                     pll_0_cam3_clk.clk
		.pll_0_cam_clk_clk                              (<connected-to-pll_0_cam_clk_clk>),                              //                      pll_0_cam_clk.clk
		.pll_0_outclk1_clk                              (<connected-to-pll_0_outclk1_clk>),                              //                      pll_0_outclk1.clk
		.reset_reset_n                                  (<connected-to-reset_reset_n>),                                  //                              reset.reset_n
		.vga_controller_0_conduit_debug_fifo_empty      (<connected-to-vga_controller_0_conduit_debug_fifo_empty>),      //     vga_controller_0_conduit_debug.fifo_empty
		.vga_controller_0_conduit_debug_fifo_full       (<connected-to-vga_controller_0_conduit_debug_fifo_full>),       //                                   .fifo_full
		.vga_controller_0_conduit_debug_fifo_half       (<connected-to-vga_controller_0_conduit_debug_fifo_half>),       //                                   .fifo_half
		.vga_controller_0_conduit_debug_waitreq         (<connected-to-vga_controller_0_conduit_debug_waitreq>),         //                                   .waitreq
		.vga_controller_0_conduit_debug_readvalid       (<connected-to-vga_controller_0_conduit_debug_readvalid>),       //                                   .readvalid
		.vga_controller_0_conduit_debug_disp_com        (<connected-to-vga_controller_0_conduit_debug_disp_com>),        //                                   .disp_com
		.vga_controller_0_conduit_debug_disp_stat       (<connected-to-vga_controller_0_conduit_debug_disp_stat>),       //                                   .disp_stat
		.vga_controller_0_conduit_debug_burst_count     (<connected-to-vga_controller_0_conduit_debug_burst_count>),     //                                   .burst_count
		.vga_controller_0_conduit_debug_read            (<connected-to-vga_controller_0_conduit_debug_read>),            //                                   .read
		.vga_controller_0_conduit_debug_state           (<connected-to-vga_controller_0_conduit_debug_state>),           //                                   .state
		.vga_controller_0_conduit_vga_board_id          (<connected-to-vga_controller_0_conduit_vga_board_id>),          //       vga_controller_0_conduit_vga.board_id
		.vga_controller_0_conduit_vga_vga_scl           (<connected-to-vga_controller_0_conduit_vga_vga_scl>),           //                                   .vga_scl
		.vga_controller_0_conduit_vga_vga_sda           (<connected-to-vga_controller_0_conduit_vga_vga_sda>),           //                                   .vga_sda
		.vga_controller_0_conduit_vga_vga_video_b       (<connected-to-vga_controller_0_conduit_vga_vga_video_b>),       //                                   .vga_video_b
		.vga_controller_0_conduit_vga_vga_clk           (<connected-to-vga_controller_0_conduit_vga_vga_clk>),           //                                   .vga_clk
		.vga_controller_0_conduit_vga_vga_video_g       (<connected-to-vga_controller_0_conduit_vga_vga_video_g>),       //                                   .vga_video_g
		.vga_controller_0_conduit_vga_vga_hsync         (<connected-to-vga_controller_0_conduit_vga_vga_hsync>),         //                                   .vga_hsync
		.vga_controller_0_conduit_vga_vga_video_r       (<connected-to-vga_controller_0_conduit_vga_vga_video_r>),       //                                   .vga_video_r
		.vga_controller_0_conduit_vga_vga_vsync         (<connected-to-vga_controller_0_conduit_vga_vga_vsync>),         //                                   .vga_vsync
		.pll_0_cam4_clk_clk                             (<connected-to-pll_0_cam4_clk_clk>)                              //                     pll_0_cam4_clk.clk
	);

