# TCL File Generated by Component Editor 16.0
# Fri Dec 23 09:28:22 CET 2016
# DO NOT MODIFY


# 
# camera_controller "camera_controller" v1.0
#  2016.12.23.09:28:22
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module camera_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME camera_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_controller.vhd VHDL PATH ../hdl/cam/camera_controller.vhd TOP_LEVEL_FILE
add_fileset_file camera_master.vhd VHDL PATH ../hdl/cam/camera_master.vhd
add_fileset_file camera_sampler.vhd VHDL PATH ../hdl/cam/camera_sampler.vhd
add_fileset_file camera_sampler_converter.vhd VHDL PATH ../hdl/cam/camera_sampler_converter.vhd
add_fileset_file camera_sampler_fsm.vhd VHDL PATH ../hdl/cam/camera_sampler_fsm.vhd
add_fileset_file camera_sampler_sync.vhd VHDL PATH ../hdl/cam/camera_sampler_sync.vhd
add_fileset_file camera_slave.vhd VHDL PATH ../hdl/cam/camera_slave.vhd
add_fileset_file camera_slave_regmap.vhd VHDL PATH ../hdl/cam/camera_slave_regmap.vhd
add_fileset_file FIFO_one_clock.vhd VHDL PATH ip/FIFO_one_clock/FIFO_one_clock.vhd
add_fileset_file FIFO_two_clock.vhd VHDL PATH ip/FIFO_two_clock/FIFO_two_clock.vhd


# 
# parameters
# 
add_parameter NBITS_CAM NATURAL 8
set_parameter_property NBITS_CAM DEFAULT_VALUE 8
set_parameter_property NBITS_CAM DISPLAY_NAME NBITS_CAM
set_parameter_property NBITS_CAM TYPE NATURAL
set_parameter_property NBITS_CAM UNITS None
set_parameter_property NBITS_CAM ALLOWED_RANGES 0:2147483647
set_parameter_property NBITS_CAM HDL_PARAMETER true
add_parameter NBITS_INT NATURAL 8
set_parameter_property NBITS_INT DEFAULT_VALUE 8
set_parameter_property NBITS_INT DISPLAY_NAME NBITS_INT
set_parameter_property NBITS_INT TYPE NATURAL
set_parameter_property NBITS_INT UNITS None
set_parameter_property NBITS_INT ALLOWED_RANGES 0:2147483647
set_parameter_property NBITS_INT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_Address address Input 4
add_interface_port avalon_slave_0 avs_ChipSelect chipselect Input 1
add_interface_port avalon_slave_0 avs_Read read Input 1
add_interface_port avalon_slave_0 avs_Write write Input 1
add_interface_port avalon_slave_0 avs_WriteData writedata Input 32
add_interface_port avalon_slave_0 avs_ReadData readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master am_Addr address Output 32
add_interface_port avalon_master am_BurstCount burstcount Output 6
add_interface_port avalon_master am_DataWrite writedata Output 32
add_interface_port avalon_master am_WaitRequest waitrequest Input 1
add_interface_port avalon_master am_Write write Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_camera
# 
add_interface conduit_camera conduit end
set_interface_property conduit_camera associatedClock clock_sink
set_interface_property conduit_camera associatedReset reset_sink
set_interface_property conduit_camera ENABLED true
set_interface_property conduit_camera EXPORT_OF ""
set_interface_property conduit_camera PORT_NAME_MAP ""
set_interface_property conduit_camera CMSIS_SVD_VARIABLES ""
set_interface_property conduit_camera SVD_ADDRESS_GROUP ""

add_interface_port conduit_camera pixclk pixclk Input 1
add_interface_port conduit_camera frame_valid frame_valid Input 1
add_interface_port conduit_camera line_valid line_valid Input 1
add_interface_port conduit_camera cam_reset cam_reset Output 1
add_interface_port conduit_camera data_in data_in Input nbits_cam


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk50 clk Input 1

